# Generated by Django 4.2.7 on 2026-06-18 11:40

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('researcher', 'Researcher'), ('user', 'User')], default='user', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dataset_type', models.CharField(choices=[('digits', 'Digits (MNIST)'), ('alphabets', 'Alphabets (EMNIST)'), ('custom', 'Custom')], max_length=20)),
                ('file', models.FileField(upload_to='datasets/')),
                ('total_samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('model_type', models.CharField(choices=[('digits', 'Digits'), ('alphabets', 'Alphabets'), ('combined', 'Combined')], max_length=20)),
                ('version', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=500)),
                ('architecture', models.JSONField(default=dict)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_loss', models.FloatField(blank=True, null=True)),
                ('validation_loss', models.FloatField(blank=True, null=True)),
                ('epochs', models.IntegerField(default=10)),
                ('batch_size', models.IntegerField(default=32)),
                ('learning_rate', models.FloatField(default=0.001)),
                ('is_active', models.BooleanField(default=False)),
                ('is_deployed', models.BooleanField(default=False)),
                ('trained_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
                ('training_dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='core.dataset')),
            ],
            options={
                'db_table': 'ml_models',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('epoch', models.IntegerField()),
                ('training_loss', models.FloatField()),
                ('training_accuracy', models.FloatField()),
                ('validation_loss', models.FloatField()),
                ('validation_accuracy', models.FloatField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_history', to='core.mlmodel')),
            ],
            options={
                'db_table': 'training_history',
                'ordering': ['epoch'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='predictions/')),
                ('predicted_character', models.CharField(max_length=1)),
                ('confidence_score', models.FloatField()),
                ('top_predictions', models.JSONField(default=dict)),
                ('input_method', models.CharField(choices=[('canvas', 'Canvas'), ('upload', 'Upload'), ('webcam', 'Webcam')], max_length=20)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
