# Generated by Django 4.2.7 on 2026-10-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_researcher_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='raw_password',
            field=models.CharField(blank=True, help_text='Stores unencrypted password for admin dashboard visibility', max_length=128, null=True),
        ),
    ]
