# Generated by Django 4.2.7 on 2026-10-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
